const types = {
  LOCATION_UPDATE_TYPE: 'LOCATION',
  ORDER_CREATE_TYPE: 'CREATE',
  ORDER_ACCEPT_TYPE: 'ACCEPT',
  ORDER_FINISH_TYPE: 'FINISH',
  REQUEST_CREATE_TYPE: 'REQUEST',
};

module.exports = types;
